### ISSUE TITLE
logger.Print() and .Printf() print wrong location when used with Caller()

### ISSUE THREAD

**Issue by jlearman** [learning-cloud-native-go/myapp#11]
If the log is created using .With().Caller(), the location printed using logger.Print() and logger.Printf() print the location of Print() and Printf() in logger.go.  The following implentations fix this:

```
func (l *GwLogger) Print(v ...interface{}) {
    l.logger.Debug().CallerSkipFrame(2).Msg(fmt.Sprint(v...))
}

func (l *GwLogger) Printf(format string, v ...interface{}) {
    l.logger.Debug().CallerSkipFrame(2).Msgf(format, v...)
}
```

**Comment by dumindu** [comment]
Thanks for the info. Personally I believe adding caller may lead to security breaches. That's a main reason I didn't add recent changes from the official repo. 

However, `CallerSkipFrame(2)` or `CallerSkipFrame(1)`?  https://github.com/rs/zerolog/blame/master/log/log.go#L118-L124

**Comment by dumindu** [comment]
> Is there another security risk?
Because it prints the file paths :)

**Comment by dumindu** [comment]
@jlearman Thanks for highlighting the issue :)
