### ISSUE TITLE
MySQL fails to launch

### ISSUE THREAD

**Issue by kstenerud** [learning-cloud-native-go/myapp#6]
```
$ docker-compose up
Starting myapp_db_1 ... done
Starting myapp_app_1 ... done
Attaching to myapp_db_1, myapp_app_1
db_1   | [i] mysqld already present, skipping creation
db_1   | [i] MySQL data directory not found, creating initial DBs
db_1   | 2020-03-20  9:40:12 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
db_1   | 2020-03-20  9:40:12 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
app_1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
app_1  | MySQL is unavailable - sleeping
db_1   | 2020-03-20  9:40:14 0 [ERROR] Plugin 'InnoDB' init function returned error.
db_1   | 2020-03-20  9:40:14 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1   | 2020-03-20  9:40:14 0 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1   | 2020-03-20  9:40:14 0 [ERROR] Aborting
```

It does this a few times, then repeats this message until stopped:

```
app_1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
app_1  | MySQL is unavailable - sleeping
app_1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
app_1  | MySQL is unavailable - sleeping
app_1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
app_1  | MySQL is unavailable - sleeping
```

**Comment by dumindu** [comment]
Run `docker-compose down` every time before up. But this will clear the data in the local DB.

**Comment by dumindu** [comment]
@kstenerud I've added separate docker files for [dev](https://github.com/learning-cloud-native-go/myapp/blob/master/docker/app/Dockerfile) and [production](https://github.com/learning-cloud-native-go/myapp/blob/master/docker/app/prod.Dockerfile). 

- We use a local DB only on dev env, so we always start work on a fresh DB every time. So this is a design decision. 
- On production env usually we mange the database separately via Google Cloud SQL or Amazon RDS.

So dev time, 
Run `docker-compose down` every time before up.

**Comment by dumindu** [comment]
Also you can see initial Kubernetes files in https://github.com/learning-cloud-native-go/myapp/tree/k8s/k8s if you are planning to use k8s cluster env for production.

**Comment by dumindu** [comment]
@kstenerud You may like this addition ; https://github.com/learning-cloud-native-go/myapp/commit/5f0545df9f9c80a2cb9b620593e0958beffd1080
